// AUTO-GENERATED by scripts/gen-seti-icons.mjs — do not edit by hand.
// Source: Seti UI (jesseweed/seti-ui, MIT) via VSCode theme-seti; the languageIds
// layer is flattened into extensions/filenames using VSCode's builtin language
// contributions. Regenerate: node scripts/gen-seti-icons.mjs [vscode-checkout].

/** One Seti glyph: a codepoint into the bundled `seti.woff` font, plus its colour. */
export interface SetiIconDef {
  code: number;
  color?: string;
}

export const setiIconDefinitions: Record<string, SetiIconDef> = {
  "_argdown": {
    "code": 57347,
    "color": "#519aba"
  },
  "_asm": {
    "code": 57348,
    "color": "#cc3e44"
  },
  "_audio": {
    "code": 57349,
    "color": "#a074c4"
  },
  "_babel": {
    "code": 57350,
    "color": "#cbcb41"
  },
  "_bazel": {
    "code": 57351,
    "color": "#8dc149"
  },
  "_bazel_1": {
    "code": 57351,
    "color": "#4d5a5e"
  },
  "_bicep": {
    "code": 57352,
    "color": "#519aba"
  },
  "_bower": {
    "code": 57353,
    "color": "#e37933"
  },
  "_bsl": {
    "code": 57354,
    "color": "#cc3e44"
  },
  "_c": {
    "code": 57356,
    "color": "#519aba"
  },
  "_c_1": {
    "code": 57356,
    "color": "#a074c4"
  },
  "_c_2": {
    "code": 57356,
    "color": "#cbcb41"
  },
  "_c-sharp": {
    "code": 57355,
    "color": "#519aba"
  },
  "_cake": {
    "code": 57357,
    "color": "#cc3e44"
  },
  "_cake_php": {
    "code": 57358,
    "color": "#cc3e44"
  },
  "_clock": {
    "code": 57362,
    "color": "#519aba"
  },
  "_clock_1": {
    "code": 57362,
    "color": "#6d8086"
  },
  "_clojure": {
    "code": 57363,
    "color": "#8dc149"
  },
  "_clojure_1": {
    "code": 57363,
    "color": "#519aba"
  },
  "_code-climate": {
    "code": 57364,
    "color": "#8dc149"
  },
  "_code-search": {
    "code": 57365,
    "color": "#a074c4"
  },
  "_coffee": {
    "code": 57366,
    "color": "#cbcb41"
  },
  "_coldfusion": {
    "code": 57368,
    "color": "#519aba"
  },
  "_config": {
    "code": 57369,
    "color": "#6d8086"
  },
  "_cpp": {
    "code": 57370,
    "color": "#519aba"
  },
  "_cpp_1": {
    "code": 57370,
    "color": "#a074c4"
  },
  "_cpp_2": {
    "code": 57370,
    "color": "#cbcb41"
  },
  "_crystal": {
    "code": 57371,
    "color": "#d4d7d6"
  },
  "_crystal_embedded": {
    "code": 57372,
    "color": "#d4d7d6"
  },
  "_css": {
    "code": 57373,
    "color": "#519aba"
  },
  "_csv": {
    "code": 57374,
    "color": "#8dc149"
  },
  "_cu": {
    "code": 57375,
    "color": "#8dc149"
  },
  "_cu_1": {
    "code": 57375,
    "color": "#a074c4"
  },
  "_d": {
    "code": 57376,
    "color": "#cc3e44"
  },
  "_dart": {
    "code": 57377,
    "color": "#519aba"
  },
  "_db": {
    "code": 57378,
    "color": "#f55385"
  },
  "_db_1": {
    "code": 57378,
    "color": "#519aba"
  },
  "_default": {
    "code": 57379,
    "color": "#d4d7d6"
  },
  "_docker": {
    "code": 57381,
    "color": "#519aba"
  },
  "_docker_1": {
    "code": 57381,
    "color": "#4d5a5e"
  },
  "_docker_2": {
    "code": 57381,
    "color": "#8dc149"
  },
  "_docker_3": {
    "code": 57381,
    "color": "#f55385"
  },
  "_ejs": {
    "code": 57383,
    "color": "#cbcb41"
  },
  "_elixir": {
    "code": 57384,
    "color": "#a074c4"
  },
  "_elixir_script": {
    "code": 57385,
    "color": "#a074c4"
  },
  "_elm": {
    "code": 57386,
    "color": "#519aba"
  },
  "_eslint": {
    "code": 57388,
    "color": "#a074c4"
  },
  "_eslint_1": {
    "code": 57388,
    "color": "#4d5a5e"
  },
  "_ethereum": {
    "code": 57389,
    "color": "#519aba"
  },
  "_f-sharp": {
    "code": 57390,
    "color": "#519aba"
  },
  "_favicon": {
    "code": 57391,
    "color": "#cbcb41"
  },
  "_firebase": {
    "code": 57392,
    "color": "#e37933"
  },
  "_firefox": {
    "code": 57393,
    "color": "#e37933"
  },
  "_font": {
    "code": 57395,
    "color": "#cc3e44"
  },
  "_git": {
    "code": 57396,
    "color": "#41535b"
  },
  "_github": {
    "code": 57399,
    "color": "#d4d7d6"
  },
  "_gitlab": {
    "code": 57400,
    "color": "#e37933"
  },
  "_go": {
    "code": 57401,
    "color": "#519aba"
  },
  "_go2": {
    "code": 57402,
    "color": "#519aba"
  },
  "_godot": {
    "code": 57403,
    "color": "#519aba"
  },
  "_godot_1": {
    "code": 57403,
    "color": "#cc3e44"
  },
  "_godot_2": {
    "code": 57403,
    "color": "#cbcb41"
  },
  "_godot_3": {
    "code": 57403,
    "color": "#a074c4"
  },
  "_gradle": {
    "code": 57404,
    "color": "#519aba"
  },
  "_grails": {
    "code": 57405,
    "color": "#8dc149"
  },
  "_graphql": {
    "code": 57406,
    "color": "#f55385"
  },
  "_grunt": {
    "code": 57407,
    "color": "#e37933"
  },
  "_gulp": {
    "code": 57408,
    "color": "#cc3e44"
  },
  "_hacklang": {
    "code": 57409,
    "color": "#e37933"
  },
  "_haml": {
    "code": 57410,
    "color": "#cc3e44"
  },
  "_happenings": {
    "code": 57411,
    "color": "#519aba"
  },
  "_haskell": {
    "code": 57412,
    "color": "#a074c4"
  },
  "_haxe": {
    "code": 57413,
    "color": "#e37933"
  },
  "_haxe_1": {
    "code": 57413,
    "color": "#cbcb41"
  },
  "_haxe_2": {
    "code": 57413,
    "color": "#519aba"
  },
  "_haxe_3": {
    "code": 57413,
    "color": "#a074c4"
  },
  "_heroku": {
    "code": 57414,
    "color": "#a074c4"
  },
  "_hex": {
    "code": 57415,
    "color": "#cc3e44"
  },
  "_html": {
    "code": 57416,
    "color": "#519aba"
  },
  "_html_1": {
    "code": 57416,
    "color": "#8dc149"
  },
  "_html_2": {
    "code": 57416,
    "color": "#cbcb41"
  },
  "_html_3": {
    "code": 57416,
    "color": "#e37933"
  },
  "_html_erb": {
    "code": 57417,
    "color": "#cc3e44"
  },
  "_ignored": {
    "code": 57418,
    "color": "#41535b"
  },
  "_illustrator": {
    "code": 57419,
    "color": "#cbcb41"
  },
  "_image": {
    "code": 57420,
    "color": "#a074c4"
  },
  "_info": {
    "code": 57421,
    "color": "#519aba"
  },
  "_ionic": {
    "code": 57422,
    "color": "#519aba"
  },
  "_jade": {
    "code": 57423,
    "color": "#cc3e44"
  },
  "_java": {
    "code": 57424,
    "color": "#cc3e44"
  },
  "_java_1": {
    "code": 57424,
    "color": "#519aba"
  },
  "_javascript": {
    "code": 57425,
    "color": "#cbcb41"
  },
  "_javascript_1": {
    "code": 57425,
    "color": "#e37933"
  },
  "_javascript_2": {
    "code": 57425,
    "color": "#519aba"
  },
  "_jenkins": {
    "code": 57426,
    "color": "#cc3e44"
  },
  "_jinja": {
    "code": 57427,
    "color": "#cc3e44"
  },
  "_json": {
    "code": 57429,
    "color": "#cbcb41"
  },
  "_json_1": {
    "code": 57429,
    "color": "#8dc149"
  },
  "_julia": {
    "code": 57430,
    "color": "#a074c4"
  },
  "_karma": {
    "code": 57431,
    "color": "#8dc149"
  },
  "_kotlin": {
    "code": 57432,
    "color": "#e37933"
  },
  "_less": {
    "code": 57433,
    "color": "#519aba"
  },
  "_license": {
    "code": 57434,
    "color": "#cbcb41"
  },
  "_license_1": {
    "code": 57434,
    "color": "#e37933"
  },
  "_license_2": {
    "code": 57434,
    "color": "#cc3e44"
  },
  "_liquid": {
    "code": 57435,
    "color": "#8dc149"
  },
  "_livescript": {
    "code": 57436,
    "color": "#519aba"
  },
  "_lock": {
    "code": 57437,
    "color": "#8dc149"
  },
  "_lua": {
    "code": 57438,
    "color": "#519aba"
  },
  "_makefile": {
    "code": 57439,
    "color": "#e37933"
  },
  "_makefile_1": {
    "code": 57439,
    "color": "#a074c4"
  },
  "_makefile_2": {
    "code": 57439,
    "color": "#6d8086"
  },
  "_makefile_3": {
    "code": 57439,
    "color": "#519aba"
  },
  "_markdown": {
    "code": 57440,
    "color": "#519aba"
  },
  "_maven": {
    "code": 57441,
    "color": "#cc3e44"
  },
  "_mdo": {
    "code": 57442,
    "color": "#cc3e44"
  },
  "_mustache": {
    "code": 57443,
    "color": "#e37933"
  },
  "_nim": {
    "code": 57445,
    "color": "#cbcb41"
  },
  "_notebook": {
    "code": 57446,
    "color": "#519aba"
  },
  "_npm": {
    "code": 57447,
    "color": "#41535b"
  },
  "_npm_1": {
    "code": 57447,
    "color": "#cc3e44"
  },
  "_npm_ignored": {
    "code": 57448,
    "color": "#41535b"
  },
  "_nunjucks": {
    "code": 57449,
    "color": "#8dc149"
  },
  "_ocaml": {
    "code": 57450,
    "color": "#e37933"
  },
  "_odata": {
    "code": 57451,
    "color": "#e37933"
  },
  "_pddl": {
    "code": 57452,
    "color": "#a074c4"
  },
  "_pdf": {
    "code": 57453,
    "color": "#cc3e44"
  },
  "_perl": {
    "code": 57454,
    "color": "#519aba"
  },
  "_photoshop": {
    "code": 57455,
    "color": "#519aba"
  },
  "_php": {
    "code": 57456,
    "color": "#a074c4"
  },
  "_pipeline": {
    "code": 57457,
    "color": "#e37933"
  },
  "_plan": {
    "code": 57458,
    "color": "#8dc149"
  },
  "_platformio": {
    "code": 57459,
    "color": "#e37933"
  },
  "_powershell": {
    "code": 57460,
    "color": "#519aba"
  },
  "_prisma": {
    "code": 57461,
    "color": "#519aba"
  },
  "_prolog": {
    "code": 57463,
    "color": "#e37933"
  },
  "_pug": {
    "code": 57464,
    "color": "#cc3e44"
  },
  "_puppet": {
    "code": 57465,
    "color": "#cbcb41"
  },
  "_purescript": {
    "code": 57466,
    "color": "#d4d7d6"
  },
  "_python": {
    "code": 57467,
    "color": "#519aba"
  },
  "_R": {
    "code": 57345,
    "color": "#519aba"
  },
  "_react": {
    "code": 57469,
    "color": "#519aba"
  },
  "_react_1": {
    "code": 57469,
    "color": "#e37933"
  },
  "_reasonml": {
    "code": 57470,
    "color": "#cc3e44"
  },
  "_rescript": {
    "code": 57471,
    "color": "#cc3e44"
  },
  "_rescript_1": {
    "code": 57471,
    "color": "#f55385"
  },
  "_rollup": {
    "code": 57472,
    "color": "#cc3e44"
  },
  "_ruby": {
    "code": 57473,
    "color": "#cc3e44"
  },
  "_rust": {
    "code": 57474,
    "color": "#6d8086"
  },
  "_salesforce": {
    "code": 57475,
    "color": "#519aba"
  },
  "_sass": {
    "code": 57476,
    "color": "#f55385"
  },
  "_sbt": {
    "code": 57477,
    "color": "#519aba"
  },
  "_scala": {
    "code": 57478,
    "color": "#cc3e44"
  },
  "_shell": {
    "code": 57481,
    "color": "#8dc149"
  },
  "_slim": {
    "code": 57482,
    "color": "#e37933"
  },
  "_smarty": {
    "code": 57483,
    "color": "#cbcb41"
  },
  "_spring": {
    "code": 57484,
    "color": "#8dc149"
  },
  "_stylelint": {
    "code": 57485,
    "color": "#d4d7d6"
  },
  "_stylelint_1": {
    "code": 57485,
    "color": "#4d5a5e"
  },
  "_stylus": {
    "code": 57486,
    "color": "#8dc149"
  },
  "_sublime": {
    "code": 57487,
    "color": "#e37933"
  },
  "_svelte": {
    "code": 57488,
    "color": "#cc3e44"
  },
  "_svg": {
    "code": 57489,
    "color": "#a074c4"
  },
  "_svg_1": {
    "code": 57489,
    "color": "#519aba"
  },
  "_swift": {
    "code": 57490,
    "color": "#e37933"
  },
  "_terraform": {
    "code": 57491,
    "color": "#a074c4"
  },
  "_tex": {
    "code": 57492,
    "color": "#519aba"
  },
  "_tex_1": {
    "code": 57492,
    "color": "#cbcb41"
  },
  "_tex_2": {
    "code": 57492,
    "color": "#e37933"
  },
  "_tex_3": {
    "code": 57492,
    "color": "#d4d7d6"
  },
  "_todo": {
    "code": 57494
  },
  "_tsconfig": {
    "code": 57495,
    "color": "#519aba"
  },
  "_twig": {
    "code": 57496,
    "color": "#8dc149"
  },
  "_typescript": {
    "code": 57497,
    "color": "#519aba"
  },
  "_typescript_1": {
    "code": 57497,
    "color": "#e37933"
  },
  "_vala": {
    "code": 57498,
    "color": "#6d8086"
  },
  "_video": {
    "code": 57499,
    "color": "#f55385"
  },
  "_vite": {
    "code": 57500,
    "color": "#cbcb41"
  },
  "_vue": {
    "code": 57501,
    "color": "#8dc149"
  },
  "_wasm": {
    "code": 57502,
    "color": "#a074c4"
  },
  "_wat": {
    "code": 57503,
    "color": "#a074c4"
  },
  "_webpack": {
    "code": 57504,
    "color": "#519aba"
  },
  "_wgt": {
    "code": 57505,
    "color": "#519aba"
  },
  "_windows": {
    "code": 57506,
    "color": "#519aba"
  },
  "_word": {
    "code": 57507,
    "color": "#519aba"
  },
  "_xls": {
    "code": 57508,
    "color": "#8dc149"
  },
  "_xml": {
    "code": 57509,
    "color": "#e37933"
  },
  "_yarn": {
    "code": 57510,
    "color": "#519aba"
  },
  "_yml": {
    "code": 57511,
    "color": "#a074c4"
  },
  "_zig": {
    "code": 57512,
    "color": "#e37933"
  },
  "_zip": {
    "code": 57513,
    "color": "#cc3e44"
  },
  "_zip_1": {
    "code": 57513,
    "color": "#6d8086"
  }
};

/** Lowercased extension (no dot) -> icon definition id. Longest extension wins at lookup. */
export const setiByExtension: Record<string, string> = {
  "3dm": "_svg_1",
  "3ds": "_svg_1",
  "ad": "_argdown",
  "agent.md": "_markdown",
  "ai": "_illustrator",
  "apex": "_salesforce",
  "argdown": "_argdown",
  "article": "_go",
  "asax": "_html_2",
  "ascx": "_html_1",
  "asm": "_asm",
  "asp": "_html_3",
  "aspx": "_html",
  "atom": "_xml",
  "avi": "_video",
  "avif": "_image",
  "axaml": "_xml",
  "axml": "_xml",
  "babelrc": "_babel",
  "babelrc.cjs": "_babel",
  "babelrc.js": "_babel",
  "bash": "_shell",
  "bash_aliases": "_shell",
  "bash_login": "_shell",
  "bash_logout": "_shell",
  "bash_profile": "_shell",
  "bashrc": "_shell",
  "bat": "_windows",
  "bazel": "_bazel",
  "bazelignore": "_bazel",
  "bazelrc": "_bazel_1",
  "bazelversion": "_bazel",
  "bbx": "_tex_1",
  "bicep": "_bicep",
  "bowerrc": "_bower",
  "bpmn": "_xml",
  "bsl": "_bsl",
  "build": "_bazel",
  "bzl": "_bazel",
  "c": "_c",
  "c++": "_cpp",
  "c++m": "_cpp",
  "cake": "_cake",
  "cbx": "_tex_1",
  "cc": "_cpp",
  "ccm": "_cpp",
  "cer": "_lock",
  "cert": "_lock",
  "cfc": "_coldfusion",
  "cff": "_yml",
  "cfg": "_config",
  "cfm": "_coldfusion",
  "chatmode.md": "_markdown",
  "cjs": "_javascript",
  "cjs.map": "_javascript",
  "cjsx": "_react",
  "class": "_java_1",
  "classpath": "_java",
  "clj": "_clojure",
  "cljc": "_clojure",
  "cljs": "_clojure",
  "cljx": "_clojure",
  "clojure": "_clojure",
  "cls": "_salesforce",
  "cmd": "_windows",
  "cmx": "_ocaml",
  "cmxa": "_ocaml",
  "code-profile": "_json",
  "code-search": "_code-search",
  "code-workspace": "_json",
  "codeclimate.yml": "_code-climate",
  "coffee": "_coffee",
  "color-theme.json": "_json",
  "component": "_html_3",
  "conf": "_config",
  "config": "_config",
  "containerfile": "_docker",
  "copilot-instructions.md": "_markdown",
  "cpp": "_cpp",
  "cppm": "_cpp",
  "cpt": "_xml",
  "cpy": "_python",
  "cr": "_crystal",
  "crt": "_lock",
  "cs": "_c-sharp",
  "csh": "_shell",
  "cshrc": "_shell",
  "cshtml": "_html",
  "csl": "_xml",
  "cson": "_json",
  "csproj": "_xml",
  "csproj.user": "_xml",
  "css": "_css",
  "css.map": "_css",
  "csv": "_csv",
  "csx": "_c-sharp",
  "ctp": "_cake_php",
  "cts": "_typescript",
  "ctx": "_tex",
  "cu": "_cu",
  "cuh": "_cu_1",
  "cxx": "_cpp",
  "cxxm": "_cpp",
  "d": "_d",
  "dae": "_svg_1",
  "dart": "_dart",
  "directory": "_config",
  "direnv": "_config",
  "dita": "_xml",
  "ditamap": "_xml",
  "doc": "_word",
  "dockerfile": "_docker",
  "dockerignore": "_docker_1",
  "docx": "_word",
  "ds_store": "_ignored",
  "dsql": "_db",
  "dtd": "_xml",
  "dtml": "_xml",
  "dtx": "_tex_2",
  "ebuild": "_shell",
  "eclass": "_shell",
  "ecr": "_crystal_embedded",
  "editorconfig": "_config",
  "edn": "_clojure_1",
  "ejs": "_ejs",
  "elm": "_elm",
  "ent": "_xml",
  "env": "_config",
  "eot": "_font",
  "epp": "_puppet",
  "erb": "_html_erb",
  "erb.html": "_html_erb",
  "es": "_javascript",
  "es5": "_javascript",
  "es6": "_javascript",
  "es7": "_javascript",
  "eslintignore": "_eslint_1",
  "eslintrc": "_eslint",
  "eslintrc.cjs": "_eslint",
  "eslintrc.js": "_eslint",
  "eslintrc.json": "_eslint",
  "eslintrc.yaml": "_eslint",
  "eslintrc.yml": "_eslint",
  "ex": "_elixir",
  "exs": "_elixir_script",
  "eyaml": "_yml",
  "eyml": "_yml",
  "firebaserc": "_firebase",
  "fish": "_shell",
  "flac": "_audio",
  "fs": "_f-sharp",
  "fsi": "_f-sharp",
  "fsproj": "_xml",
  "fsscript": "_f-sharp",
  "fsx": "_f-sharp",
  "fxml": "_xml",
  "gd": "_godot",
  "gemspec": "_ruby",
  "geojson": "_json",
  "gif": "_image",
  "git-blame-ignore-revs": "_git",
  "gitattributes": "_git",
  "gitconfig": "_git",
  "github-issues": "_github",
  "gitignore": "_git",
  "gitignore_global": "_git",
  "gitkeep": "_git",
  "gitlab-ci.yml": "_gitlab",
  "gitmodules": "_git",
  "go": "_go2",
  "godot": "_godot_1",
  "gql": "_graphql",
  "gradle": "_gradle",
  "graphql": "_graphql",
  "graphqls": "_graphql",
  "groovy": "_grails",
  "gsp": "_grails",
  "gvy": "_grails",
  "gyp": "_python",
  "gypi": "_python",
  "h": "_c_1",
  "h.in": "_cpp",
  "h++": "_cpp_1",
  "hack": "_hacklang",
  "haml": "_haml",
  "handlebars": "_mustache",
  "happenings": "_happenings",
  "har": "_json",
  "hbs": "_mustache",
  "hh": "_cpp_1",
  "hintrc": "_json",
  "hjs": "_mustache",
  "hpp": "_cpp_1",
  "hpp.in": "_cpp",
  "hs": "_haskell",
  "htaccess": "_config",
  "htm": "_html_3",
  "html": "_html_3",
  "html.erb": "_html_erb",
  "hu": "_cu_1",
  "hx": "_haxe",
  "hxml": "_haxe_3",
  "hxp": "_haxe_2",
  "hxs": "_haxe_1",
  "hxx": "_cpp_1",
  "i": "_c",
  "iced": "_coffee",
  "ico": "_favicon",
  "icon-theme.json": "_json",
  "ii": "_cpp",
  "iml": "_xml",
  "inl": "_cpp",
  "ino": "_cpp",
  "ins": "_tex_3",
  "instructions.md": "_markdown",
  "ipp": "_cpp",
  "ipy": "_python",
  "ipynb": "_notebook",
  "isml": "_xml",
  "ixx": "_cpp",
  "jade": "_jade",
  "jar": "_zip",
  "jav": "_java",
  "java": "_java",
  "jenkinsfile": "_grails",
  "jinja": "_jinja",
  "jinja2": "_jinja",
  "jl": "_julia",
  "jmx": "_xml",
  "jpeg": "_image",
  "jpg": "_image",
  "js": "_javascript",
  "js.map": "_javascript",
  "jscsrc": "_javascript_2",
  "jsfmtrc": "_json",
  "jshintrc": "_javascript_2",
  "jshtm": "_html_3",
  "jslintrc": "_json",
  "json": "_json",
  "jsonc": "_json",
  "jsonl": "_json",
  "jsonld": "_json",
  "jsp": "_html_3",
  "jsx": "_react",
  "key": "_lock",
  "ksh": "_shell",
  "kt": "_kotlin",
  "kts": "_kotlin",
  "language-configuration.json": "_json",
  "launch": "_xml",
  "less": "_less",
  "lhs": "_haskell",
  "liquid": "_liquid",
  "litcoffee": "_coffee",
  "ls": "_livescript",
  "ltx": "_tex",
  "lua": "_lua",
  "m": "_c_2",
  "mak": "_makefile",
  "markdn": "_markdown",
  "markdown": "_markdown",
  "master": "_html_2",
  "md": "_markdown",
  "mdo": "_mdo",
  "mdoc": "_html_3",
  "mdown": "_markdown",
  "mdtext": "_markdown",
  "mdtxt": "_markdown",
  "mdwn": "_markdown",
  "menu": "_xml",
  "mjs": "_javascript",
  "mjs.map": "_javascript",
  "mk": "_makefile",
  "mkd": "_markdown",
  "mkdn": "_markdown",
  "ml": "_ocaml",
  "mli": "_ocaml",
  "mm": "_cpp_2",
  "mod": "_xml",
  "mov": "_video",
  "mp3": "_audio",
  "mp4": "_video",
  "mpg": "_video",
  "mts": "_typescript",
  "mustache": "_mustache",
  "mxml": "_xml",
  "ndjson": "_json",
  "nf": "_grails",
  "nim": "_nim",
  "nims": "_nim",
  "nj": "_nunjucks",
  "njk": "_nunjucks",
  "njs": "_nunjucks",
  "npm-debug.log": "_npm",
  "npmignore": "_npm_1",
  "npmrc": "_npm_1",
  "nunj": "_nunjucks",
  "nunjs": "_nunjucks",
  "nunjucks": "_nunjucks",
  "nuspec": "_xml",
  "obj": "_svg_1",
  "odata": "_odata",
  "ogg": "_audio",
  "ogv": "_video",
  "opml": "_xml",
  "otf": "_font",
  "owl": "_xml",
  "pac": "_javascript",
  "pddl": "_pddl",
  "pdf": "_pdf",
  "pem": "_lock",
  "php": "_php",
  "php.inc": "_php",
  "php4": "_php",
  "php5": "_php",
  "phtml": "_php",
  "pipeline": "_pipeline",
  "pl": "_perl",
  "plan": "_plan",
  "pm": "_perl",
  "png": "_image",
  "pod": "_perl",
  "podspec": "_ruby",
  "pp": "_puppet",
  "prisma": "_prisma",
  "pro": "_prolog",
  "profile": "_shell",
  "proj": "_xml",
  "prompt.md": "_markdown",
  "properties": "_config",
  "props": "_xml",
  "ps1": "_powershell",
  "psd": "_photoshop",
  "psd1": "_powershell",
  "psgi": "_perl",
  "psm1": "_powershell",
  "psrc": "_powershell",
  "pssc": "_powershell",
  "pt": "_xml",
  "publishsettings": "_xml",
  "pubxml": "_xml",
  "pubxml.user": "_xml",
  "pug": "_pug",
  "purs": "_purescript",
  "pxm": "_image",
  "py": "_python",
  "pyi": "_python",
  "pyt": "_python",
  "pyw": "_python",
  "r": "_R",
  "rake": "_ruby",
  "razor": "_html",
  "rb": "_ruby",
  "rbi": "_ruby",
  "rbx": "_ruby",
  "rbxlx": "_xml",
  "rbxmx": "_xml",
  "rdf": "_xml",
  "re": "_reasonml",
  "repo": "_config",
  "res": "_rescript",
  "resi": "_rescript_1",
  "rhistory": "_R",
  "rhtml": "_html_3",
  "rjs": "_ruby",
  "rmd": "_R",
  "rng": "_xml",
  "ron": "_markdown",
  "ronn": "_markdown",
  "rprofile": "_R",
  "rpy": "_python",
  "rs": "_rust",
  "rss": "_xml",
  "rt": "_R",
  "ru": "_ruby",
  "s": "_asm",
  "sass": "_sass",
  "sbt": "_sbt",
  "scala": "_scala",
  "scss": "_sass",
  "sh": "_shell",
  "shproj": "_xml",
  "shtml": "_html_3",
  "slang": "_crystal_embedded",
  "slide": "_go",
  "slim": "_slim",
  "slnx": "_xml",
  "slugignore": "_config",
  "smarty.tpl": "_smarty",
  "sol": "_ethereum",
  "soql": "_db_1",
  "spec.cjs": "_javascript_1",
  "spec.js": "_javascript_1",
  "spec.jsx": "_react_1",
  "spec.mjs": "_javascript_1",
  "spec.ts": "_typescript_1",
  "spec.tsx": "_react_1",
  "springbeans": "_spring",
  "sql": "_db",
  "sss": "_css",
  "stache": "_mustache",
  "static": "_config",
  "stl": "_svg_1",
  "storyboard": "_xml",
  "sty": "_tex_1",
  "styl": "_stylus",
  "stylelintignore": "_stylelint_1",
  "stylelintrc": "_stylelint",
  "stylelintrc.js": "_stylelint",
  "stylelintrc.json": "_stylelint",
  "stylelintrc.yaml": "_stylelint",
  "stylelintrc.yml": "_stylelint",
  "sublime-project": "_sublime",
  "sublime-workspace": "_sublime",
  "svelte": "_svelte",
  "svg": "_svg",
  "svgx": "_image",
  "swcrc": "_json",
  "swift": "_swift",
  "t": "_perl",
  "targets": "_xml",
  "tcshrc": "_shell",
  "test.cjs": "_javascript_1",
  "test.js": "_javascript_1",
  "test.jsx": "_react_1",
  "test.mjs": "_javascript_1",
  "test.ts": "_typescript_1",
  "test.tsx": "_react_1",
  "tex": "_tex",
  "tf": "_terraform",
  "tf.json": "_terraform",
  "tfvars": "_terraform",
  "tfvars.json": "_terraform",
  "tiff": "_image",
  "tld": "_xml",
  "tmp": "_clock_1",
  "tmx": "_xml",
  "toml": "_config",
  "toolset.jsonc": "_json",
  "tpl": "_smarty",
  "tpp": "_cpp",
  "tres": "_godot_2",
  "ts": "_typescript",
  "ts.map": "_json",
  "tsbuildinfo": "_json",
  "tscn": "_godot_3",
  "tsx": "_react",
  "ttf": "_font",
  "twig": "_twig",
  "txx": "_cpp",
  "vala": "_vala",
  "vapi": "_vala",
  "vbproj": "_xml",
  "vbproj.user": "_xml",
  "vcxproj": "_xml",
  "vcxproj.filters": "_xml",
  "volt": "_html_3",
  "vue": "_vue",
  "vuerc": "_json",
  "wasm": "_wasm",
  "wat": "_wat",
  "wav": "_audio",
  "webm": "_video",
  "webmanifest": "_json",
  "webp": "_image",
  "wgt": "_wgt",
  "winget": "_yml",
  "woff": "_font",
  "woff2": "_font",
  "workbook": "_markdown",
  "workspace": "_bazel",
  "wsdl": "_xml",
  "wxi": "_xml",
  "wxl": "_xml",
  "wxs": "_xml",
  "xaml": "_xml",
  "xbl": "_xml",
  "xht": "_html_3",
  "xhtml": "_html_3",
  "xib": "_xml",
  "xlf": "_xml",
  "xliff": "_xml",
  "xls": "_xls",
  "xlsx": "_xls",
  "xml": "_xml",
  "xoml": "_xml",
  "xpdl": "_xml",
  "xprofile": "_shell",
  "xsd": "_xml",
  "xsession": "_shell",
  "xsessionrc": "_shell",
  "xul": "_xml",
  "yaml": "_yml",
  "yaml-tmlanguage": "_yml",
  "yaml-tmpreferences": "_yml",
  "yaml-tmtheme": "_yml",
  "yash_profile": "_shell",
  "yashrc": "_shell",
  "yml": "_yml",
  "zig": "_zig",
  "zip": "_zip_1",
  "zlogin": "_shell",
  "zlogout": "_shell",
  "zprofile": "_shell",
  "zsh": "_shell",
  "zsh-theme": "_shell",
  "zshenv": "_shell",
  "zshrc": "_shell"
};

/** Lowercased full filename -> icon definition id. Beats extension matches. */
export const setiByFileName: Record<string, string> = {
  ".babelrc.json": "_json",
  ".devcontainer.json": "_json",
  ".ember-cli": "_json",
  ".env": "_config",
  ".envrc": "_shell",
  ".flaskenv": "_config",
  ".hushlogin": "_shell",
  ".vscodeignore": "_git",
  ".watchmanconfig": "_json",
  "apkbuild": "_shell",
  "appfile": "_ruby",
  "appraisals": "_ruby",
  "argv.json": "_json",
  "babel.config.cjs": "_babel",
  "babel.config.js": "_babel",
  "babel.config.json": "_babel",
  "bashrc_apple_terminal": "_shell",
  "berksfile": "_ruby",
  "berksfile.lock": "_ruby",
  "bower.json": "_bower",
  "brewfile": "_ruby",
  "build": "_bazel",
  "build.bazel": "_bazel",
  "bun.lock": "_json",
  "capfile": "_ruby",
  "changelog": "_clock",
  "changelog.md": "_clock",
  "changelog.txt": "_clock",
  "changes": "_clock",
  "changes.md": "_clock",
  "changes.txt": "_clock",
  "cheffile": "_ruby",
  "cmakelists.txt": "_makefile_3",
  "commit_editmsg": "_git",
  "compiling": "_license_1",
  "compiling.md": "_license_1",
  "compiling.txt": "_license_1",
  "composer.lock": "_json",
  "containerfile": "_docker",
  "contributing": "_license_2",
  "contributing.md": "_license_2",
  "contributing.txt": "_license_2",
  "copying": "_license",
  "copying.md": "_license",
  "copying.txt": "_license",
  "dangerfile": "_ruby",
  "deliverfile": "_ruby",
  "devcontainer.json": "_json",
  "docker-healthcheck": "_docker_2",
  "dockerfile": "_docker",
  "eslint.config.js": "_eslint",
  "extensions.json": "_json",
  "fastfile": "_ruby",
  "firebase.json": "_firebase",
  "geckodriver": "_firefox",
  "gemfile": "_ruby",
  "gitconfig": "_config",
  "gnumakefile": "_makefile",
  "gruntfile.babel.js": "_grunt",
  "gruntfile.coffee": "_grunt",
  "gruntfile.js": "_grunt",
  "guardfile": "_ruby",
  "gulpfile": "_gulp",
  "gulpfile.js": "_gulp",
  "gymfile": "_ruby",
  "hobofile": "_ruby",
  "ionic.config.json": "_ionic",
  "ionic.project": "_ionic",
  "jakefile": "_javascript",
  "jenkinsfile": "_jenkins",
  "jsconfig.json": "_json",
  "karma.conf.cjs": "_karma",
  "karma.conf.coffee": "_karma",
  "karma.conf.js": "_karma",
  "karma.conf.mjs": "_karma",
  "keybindings.json": "_json",
  "launch.json": "_json",
  "licence": "_license",
  "licence.md": "_license",
  "licence.txt": "_license",
  "license": "_license",
  "license.md": "_license",
  "license.txt": "_license",
  "makefile": "_makefile",
  "matchfile": "_ruby",
  "mcp.json": "_json",
  "merge_msg": "_git",
  "mime.types": "_config",
  "mix": "_hex",
  "mvnw": "_maven",
  "npm-debug.log": "_npm_ignored",
  "ocamlmakefile": "_makefile",
  "omakefile": "_makefile_2",
  "pkgbuild": "_shell",
  "platformio.ini": "_platformio",
  "podfile": "_ruby",
  "pom.xml": "_maven",
  "procfile": "_heroku",
  "profiles.json": "_json",
  "puppetfile": "_ruby",
  "qmakefile": "_makefile_1",
  "rakefile": "_ruby",
  "rantfile": "_ruby",
  "readme": "_info",
  "readme.md": "_info",
  "readme.txt": "_info",
  "rollup.config.js": "_rollup",
  "sass-lint.yml": "_sass",
  "scanfile": "_ruby",
  "sconscript": "_python",
  "sconstruct": "_python",
  "settings.json": "_json",
  "skill.md": "_markdown",
  "snapfile": "_ruby",
  "stylelint.config.cjs": "_stylelint",
  "stylelint.config.js": "_stylelint",
  "stylelint.config.mjs": "_stylelint",
  "swagger.json": "_json_1",
  "swagger.yaml": "_json_1",
  "swagger.yml": "_json_1",
  "tasks.json": "_json",
  "thorfile": "_ruby",
  "todo": "_todo",
  "todo.md": "_todo",
  "todo.txt": "_todo",
  "tsconfig.json": "_tsconfig",
  "typedoc.json": "_json",
  "user-dirs.dirs": "_config",
  "vagrantfile": "_ruby",
  "version": "_clock",
  "version.md": "_clock",
  "version.txt": "_clock",
  "vite.config.cjs": "_vite",
  "vite.config.cts": "_vite",
  "vite.config.js": "_vite",
  "vite.config.mjs": "_vite",
  "vite.config.mts": "_vite",
  "vite.config.ts": "_vite",
  "webpack.common.cjs": "_webpack",
  "webpack.common.js": "_webpack",
  "webpack.common.mjs": "_webpack",
  "webpack.common.ts": "_webpack",
  "webpack.config.build.cjs": "_webpack",
  "webpack.config.build.js": "_webpack",
  "webpack.config.build.mjs": "_webpack",
  "webpack.config.build.ts": "_webpack",
  "webpack.config.cjs": "_webpack",
  "webpack.config.js": "_webpack",
  "webpack.config.mjs": "_webpack",
  "webpack.config.ts": "_webpack",
  "webpack.dev.cjs": "_webpack",
  "webpack.dev.js": "_webpack",
  "webpack.dev.mjs": "_webpack",
  "webpack.dev.ts": "_webpack",
  "webpack.prod.cjs": "_webpack",
  "webpack.prod.js": "_webpack",
  "webpack.prod.mjs": "_webpack",
  "webpack.prod.ts": "_webpack",
  "workspace": "_bazel",
  "workspace.bazel": "_bazel",
  "yarn.clean": "_yarn",
  "yarn.lock": "_yarn",
  "zlogin": "_shell",
  "zlogout": "_shell",
  "zprofile": "_shell",
  "zshenv": "_shell",
  "zshrc": "_shell",
  "zshrc_apple_terminal": "_shell"
};

/** Fallback icon definition id for files matching nothing above. */
export const setiDefaultFile = "_default";
